version: 2
jobs:
  build-and-test:
    filters:
      branches:
        only: master
    working_directory: ~/hcomments
    machine: true
    steps:
      - checkout
      - restore_cache:
          key: hcomments-{{ checksum "hcomments.cabal" }}
      - run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 575159689BEFB442
          echo 'deb http://download.fpcomplete.com/ubuntu precise main'|sudo tee /etc/apt/sources.list.d/fpco.list
          sudo apt-get update && sudo apt-get install stack -y
      - run: |
          docker info
          stack setup
      - run: |
          make
          stack test
      - save_cache:
        paths:
          - ~/.stack
          - ~/.postgres-emedded
        key: hcomments-{{ checksum "hcomments.cabal" }}
          
  deploy:
    machine: true
    steps:
      - run: |
          docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
          make push

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build-and-test
      - deploy:
          requires:
            - build-and-test
          filters:
            tags: 
              only: /release-.*/
          
